### ISSUE TITLE
[FEATURE] Sync data with webdav

### ISSUE THREAD

**Issue by Mahoo12138** [sheepzh/timer#257] opened 2024-01-12 01:19 UTC

**Comment by Mahoo12138** [comment] 2024-01-12 01:34
One more question, As a multi-browser user, I wish it can sync well in multi client.

**Comment by sheepzh** [comment] 2024-01-12 02:46
> One more question, As a multi-browser user, I wish it can sync well in multi client.

Transferring data between multiple clients requires additional state and the system becomes more complex. So this feature is prohibited by design. 

Instead, this extension simply synchronizes all clients' data into a central service.

**Comment by Mahoo12138** [comment] 2024-01-12 06:47
> > One more question, As a multi-browser user, I wish it can sync well in multi client.
> 
> Transferring data between multiple clients requires additional state and the system becomes more complex. So this feature is prohibited by design.
> 
> Instead, this extension simply synchronizes all clients' data into a central service.

Thx for your explain, I also think it is hard to function.

**Comment by sheepzh** [comment] 2024-09-08 11:20
This feature will be supported since v2.4.5

**Closed by sheepzh** 2024-09-08 11:20 UTC
Labels: feature
